### ISSUE TITLE
Error on Server Start with Version 0.65C

### ISSUE THREAD

**Issue by topthat177** [heirteir/AutoEye#1]
Hi, just uploaded the new version 0.65C and multicraft issued me with an error suggesting that the plugin isn't up to date? Error here -- https://pastebin.com/pga1XyuF

**Comment by heirteir** [comment]
I will fix this when I get home tomorrow. Thank you for bringing this to my attention.

**Comment by heirteir** [comment]
Issue is fixed in version 0.65D
