### ISSUE TITLE
Possible NoFall / Glide bypass

### ISSUE THREAD

**Issue by Alex1607** [heirteir/AutoEye#11]
## Error description

**What happend?:** The Player can slow his fall down to prevent fall damage. This could also be used to make a glide or fly.

**What should happen?:** Player should be pulled down and should not be able to "glide down"

**Video** (_not needed but very helpful_): https://dl.pluoi.com/5adbb3c6894a6.mp4

## Useful information

**Plugin Version:** 0.65D

**Server Version:** 1.8.8

**Minecraft Version:** 1.8.8

**Other Plugins:** %

**Does the Server use ViaVersion?:** Yes

**Console output** (_If the plugin throw an error in the console post the log here. Please use a [gist](https://gist.github.com/) or [pastebin](https://pastebin.com)_): %

**Comment by heirteir** [comment]
This can be done a legitimate client. There is no way for me to handle these ghost blocks for any sort of consistency.
