### ISSUE TITLE
Autoeye error on player join persisting

### ISSUE THREAD

**Issue by topthat177** [heirteir/AutoEye#12]
When a player joins the server the following error is produced in console. This happened in the previous version too.

**Plugin Version:**
0.66A

**Server Version:**
1.12.2

**Minecraft Version:**
1.12.2

**Other Plugins:**
CoreProtect, CleanroomGenerator, WorldEdit, FirstJoinPlus, BlockLocker, PlaceholderAPI, PacketListenerApi, TuxTwoLib, WhitelistPlus, NoPluginViewer, Votifier, GMC, UltimateVotes, WorldGuard, ProtocolLib, Multiverse-Core, LibsDisguises, SimpleBackup, CustomUknownCommand, DeluxeMenus, PermissionsEx, Autoeye, CustomHelp, SnowballDamage, Multiverse-Portals, ProtocolSupport, CommandButtons, ClientStats, HolographicDisplays, ProtocolSupportLegacySupport, ProtocolSupportStuff, Multiverse-NetherPortals, Vault, UltraCosmetics, Essentials, WarpGUI, PlayerWarpGUI, Jobs, PerWorldInventory, SkyWars, Citizens, Quests, EssentialsProtect, AdvancedAchievements, EssentialsChat, BetterRTP, EssentialsSpawn, EnjinMinecraftPlugin

**Does the Server use ViaVersion?:**
No, but we do run protocolsupport. 

**Console output**
https://pastebin.com/9ktTLAPY

**Comment by heirteir** [comment]
Thank you I will make sure to have this fixed in AutoEye version 0.66B.

**Comment by heirteir** [comment]
Fixed in version 0.66B
