### ISSUE TITLE
Step Bypass

### ISSUE THREAD

**Issue by Alex1607** [heirteir/AutoEye#13]
## Error description

**What happend?:** When the Player jumps against a wall he can use step about 5 to 10 block high

**What should happen?:** The Player should not be able to step so high he should be teleported down

**Video** (_not needed but very helpful_): https://dl.pluoi.com/5adc42e8a6ec5.mp4

## Useful information

**Plugin Version:** 66A

**Server Version:** 1.8.8

**Minecraft Version:** 1.8

**Other Plugins:** %

**Does the Server use ViaVersion?:** Yes

**Console output** (_If the plugin throw an error in the console post the log here. Please use a [gist](https://gist.github.com/) or [pastebin](https://pastebin.com)_): %

**Comment by heirteir** [comment]
Thank you I will make sure to have this fixed in 0.66B.

**Comment by heirteir** [comment]
Fixed in version 0.66B
