### ISSUE TITLE
Invalid Motion while jumping and placing blocks

### ISSUE THREAD

**Issue by Alex1607** [heirteir/AutoEye#15]
## Error description

**What happend?:** When a player jumps and places a block below him he gets flagged for invalid motion

**What should happen?:** The player should be able to tower normal

**Video** (_not needed but very helpful_): https://dl.pluoi.com/5ade06fc86fcb.mp4

## Useful information

**Plugin Version:** Newest

**Server Version:** 1.8.8

**Minecraft Version:** 1.8.8

**Other Plugins:** %

**Does the Server use ViaVersion?:** Yes

**Console output** (_If the plugin throw an error in the console post the log here. Please use a [gist](https://gist.github.com/) or [pastebin](https://pastebin.com)_): %

**Comment by heirteir** [comment]
Will be fixed in next commit.
