### ISSUE TITLE
Teleport bypass

### ISSUE THREAD

**Issue by Alex1607** [heirteir/AutoEye#18]
## Error description
The player can use a Teleport hack to teleport around the world. This can also work ~2 blocks up and only flags speed once.

**Video** (_not needed but very helpful_): https://dl.pluoi.com/5adf5bae112f1.mp4

## Useful information

**Plugin Version:** Newest

**Server Version:** 1.8.8

**Minecraft Version:** 1.8

**Other Plugins:** %

**Does the Server use ViaVersion?:** Yes

**Console output** (_If the plugin throw an error in the console post the log here. Please use a [gist](https://gist.github.com/) or [pastebin](https://pastebin.com)_): %

**Comment by heirteir** [comment]
Will be fixed in the next commit.
