### ISSUE TITLE
False Invalid Motion

### ISSUE THREAD

**Issue by Alex1607** [heirteir/AutoEye#19]
## Error description

After a Player gets hitted and tries to jump ge hets flagged for Invalid Motion.

**Video** (_not needed but very helpful_): https://dl.pluoi.com/5adf9322d2b3f.mp4

## Useful information

**Plugin Version:** Newest (Github Version)

**Server Version:** 1.8.8

**Minecraft Version:** 1.8

**Other Plugins:** %

**Does the Server use ViaVersion?:** No

**Console output** (_If the plugin throw an error in the console post the log here. Please use a [gist](https://gist.github.com/) or [pastebin](https://pastebin.com)_): %

**Comment by heirteir** [comment]
Will be fixed in next commit.
