### ISSUE TITLE
Invalid Motion with Portals

### ISSUE THREAD

**Issue by topthat177** [heirteir/AutoEye#20]
**What happend?:**
When entering a multiverse portal, there will be a few invalid motion spams when you land on the other side.

**Video** (_not needed but very helpful_):
https://vimeo.com/266468355

Password = autoeye

**Plugin Version:**
0.66C

**Server Version:**
1.12.2

**Minecraft Version:**

1.12.2
**Other Plugins:**
There's alot.

**Does the Server use ViaVersion?:**
ProtocolSupport

**Comment by heirteir** [comment]
Will be fixed in the next commit.
