### ISSUE TITLE
Kicked with certain right-clicks

### ISSUE THREAD

**Issue by topthat177** [heirteir/AutoEye#21]
**What happend?:**
When shifting and Right-Clicking the block directly below you you will be kicked (kick reason in vid). Also if you right click while looking in between a door and a glass pane block you will be disconnected.

**Video** (_not needed but very helpful_):
https://vimeo.com/266468196

Password = autoeye

**Plugin Version:**
0.66C

**Server Version:**
1.12.2

**Minecraft Version:**
1.12.2

**Other Plugins:**
A lot

**Does the Server use ViaVersion?:**
ProtocolSupport

**Console output** (_If the plugin throw an error in the console post the log here. Please use a [gist](https://gist.github.com/) or [pastebin](https://pastebin.com)_):

https://pastebin.com/9eKk4GjR

**Comment by Alex1607** [comment]
To be more precise with the right clicks: The Player will be kicked when the player with an item/block in his hand clicks somewhere and places nothing. Same with right clicks into the air. Also it only happens with 1.12 clients on a 1.12 server

**Comment by heirteir** [comment]
Should be fixed in the next commit.
