### ISSUE TITLE
Strange Disconnect using /spawn

### ISSUE THREAD

**Issue by topthat177** [heirteir/AutoEye#25]
**What happend?:**
This is a strange one. Disconnected when using /spawn and holding 'W' to walk forwards. Only happens in one particular world from what I've tested and only happens if you have just used the warp to this world. Not moved from the point you were warped to and then used /spawn and are walking forwards in the small period between you entering the command and actually being warped to the spawn.

**Plugin Version:**
0.67C

**Server Version:**
1.12.2

**Minecraft Version:**
1.12.2

**Other Plugins:**
alot

**Does the Server use ViaVersion?:**
ProtocolSupport
**Console output** (_If the plugin throw an error in the console post the log here. Please use a [gist](https://gist.github.com/) or [pastebin](https://pastebin.com)_):

https://pastebin.com/2SpZcJpn

**Comment by topthat177** [comment]
Actually it doesn't matter if your in the exact spot you were warped to or not but only seems to happen in one world.

**Comment by heirteir** [comment]
I can't seem to recreate this issue. Could you PM me on discord so I can get some more information?

**Comment by heirteir** [comment]
Information hasn't been provided in 2 weeks.
