### ISSUE TITLE
Speed flagged for sprinting

### ISSUE THREAD

**Issue by Alex1607** [heirteir/AutoEye#26]
## Error description

If a player is sprinting to a player, and hits him while sprinting the other player will get flagged for speed.
That's because a player gets more knockback when he's hit by a running player.

**Video** (_not needed but very helpful_): https://dl.pluoi.com/5ae3a3a33ad6a.mp4

## Useful information

**Plugin Version:** Newest

**Server Version:** 1.8.8

**Minecraft Version:** 1.8

**Other Plugins:** %

**Does the Server use ViaVersion?:** Yes

**Console output** (_If the plugin throw an error in the console post the log here. Please use a [gist](https://gist.github.com/) or [pastebin](https://pastebin.com)_): %

**Comment by heirteir** [comment]
Will be fixed in next commit.
