### ISSUE TITLE
AutoEye 0.67C - False Positives (With Video)

### ISSUE THREAD

**Issue by MCGamer00000** [heirteir/AutoEye#30]
## Error description

**What happend?:**
It created a false positive on NoSlowdown.
When flying and holding down Shift and landing on a block, it says your using NoSlowdown

It also created a false positive on Fast Ladder.
When standing inside a vine block (Not in the area for the effect of the vine, but in the block) and jumping onto the block the vine is on, can sometimes say "Fast Ladder"

It ALSO created a false positive for OnGround Spoof.
When you sneak and enter a vine (possibly ladder?) it sometimes says your using "On Ground Spoof" (Possible reasoning for this in the video)

**What should happen?:**
There shouldn't be a false positive.

**Video** (_not needed but very helpful_):
https://youtu.be/EYEM4mqi6kY

## Useful information

**Plugin Version:**
0.67C

**Server Version:**
CraftBukkit version git-Spigot-2086bb0-1988d7f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
(It is also localhost)

**Minecraft Version:**
1.12.2

**Other Plugins:**
A custom plugin that doesn't alter move events at all (It is in the video, it shows the information)
And Essentials (Which isn't required to make the false positives work)

**Does the Server use ViaVersion?:**
Nope

**Console output** (_If the plugin throw an error in the console post the log here. Please use a [gist](https://gist.github.com/) or [hastebin](https://hastebin.com)_):
No errors in console

**Comment by heirteir** [comment]
Will be fixed in next update to spigot.
