### ISSUE TITLE
Killaura false positive

### ISSUE THREAD

**Issue by Alex1607** [heirteir/AutoEye#4]
It is possible to trigger false messages when you are in an opponent and the mouse moves something with every hit. The same is also possible if you are not in the opponent but it occurs there much rarer. https://dl.pluoi.com/5ada594667378.mp4

**Comment by heirteir** [comment]
Thank you I will  make sure to fix this issue in the next update.

**Comment by heirteir** [comment]
Fixed in AutoEye version 0.66A
