### ISSUE TITLE
Jumping next to fences => false positive

### ISSUE THREAD

**Issue by antbig** [heirteir/AutoEye#7]
Detected for "spoofed on ground" and "invalid motion" when jumping next to not full block (fence, anvil)
https://youtu.be/wq_iyQXWaxU

**Comment by Alex1607** [comment]
I couldn't reproduce that. Did you do something else before the error occurred? https://dl.pluoi.com/5adb534052aca.mp4

**Comment by antbig** [comment]
No, i'm playing in 1.12.2 on an 1.8.8 server using viaversion

**Comment by Alex1607** [comment]
Strange. It looks like it is just an issue if the player is using 1.12.2. I have just tested it again with 1.12.2 and viaversion and it flagged me too. https://dl.pluoi.com/5adb55478d692.mp4

**Comment by heirteir** [comment]
Fixed in AutoEye version 0.66A
