### ISSUE TITLE
Sprinting in webs = flag

### ISSUE THREAD

**Issue by Alex1607** [heirteir/AutoEye#8]
When sprinting in a web it throws false prositives.
https://dl.pluoi.com/5adb2f6a7ade9.mp4

**Comment by heirteir** [comment]
I can't seem to recreate this issue. Could you give me some more information?

**Comment by Alex1607** [comment]
The only other information I can give you is: absClientVelocity is 0 and checkThreshold also returned true. (https://dl.pluoi.com/5adb9c77cdffc.png)
I know that absClientVelocity is 0 and that 0 in my opinion, is correct but I don't know yet why checkThreshold returns true.

**Comment by heirteir** [comment]
Ah I see what I did wrong.

**Comment by heirteir** [comment]
Fixed is AutoEye version 0.66A
