### ISSUE TITLE
Walking on bed => false positive

### ISSUE THREAD

**Issue by antbig** [heirteir/AutoEye#9]
Server version : 1.8.8
Client version : 1.12.2

Walking on a bed create detection for step

**Comment by heirteir** [comment]
You don't need to post multiple issues for the same issue. This is a viaversion issue with clients on 1.12 playing on a 1.8 server.

**Comment by Alex1607** [comment]
This is not just an issue with 1.12 and viaversion. The bug also happens on 1.8. Its a little "bug" in the step check which only allows 0.5 blocks in one go. But the bed is 0.56250 blocks high. (Idk why, minecraft is strange) That means the step check should allow 0.56250 block steps. https://dl.pluoi.com/5adb920035926.mp4

**Comment by heirteir** [comment]
Thank you, I assumed he was referring to the issue before.

**Comment by heirteir** [comment]
Fixed in Autoeye version 0.66A
